// Generated by CoffeeScript 1.3.3
(function() {
  var Api, http;

  Api = function() {};

  http = require("http");

  Api.prototype.save = function(user, callback) {
    var optionspost, req;
    user = JSON.stringify(user);
    optionspost = {
      host: "0.0.0.0",
      port: 3000,
      path: "/api/v1/user",
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Content-Length": user.length
      }
    };
    req = http.request(optionspost, function(res) {
      console.log("STATUS: " + res.statusCode);
      console.log("HEADERS: " + JSON.stringify(res.headers));
      res.setEncoding("utf8");
      return res.on("data", function(d) {
        console.info("\n\nPOST completed");
        return callback({
          status: "success"
        });
      });
    }).on("error", function(e) {
      return callback({
        status: e.message
      });
    });
    req.write(user);
    return req.end();
  };

  exports.Api = Api;

}).call(this);
