// Generated by CoffeeScript 1.3.3
(function() {
  var User, fs;

  User = require("../models/User").User;

  fs = require("fs");

  module.exports = function(app) {
    return app.post("/api/v1/user", function(req, res) {
      var name, stream, user;
      user = new User(req.body.name, req.body.email, req.body.password, req.body.imageID);
      name = user.name.replace(/\s/g, "");
      stream = fs.createWriteStream(name + ".txt");
      stream.once("open", function(fd) {
        stream.write("firstname/lastname: " + user.name + "\n");
        stream.write("email: " + user.email + "\n");
        stream.write("password: " + user.password + "\n");
        stream.write("image id: " + user.imageID + "\n");
        return stream.end();
      });
      return res.send({
        status: "success"
      });
    });
  };

}).call(this);
