// Generated by CoffeeScript 1.3.3
(function() {
  var Api, User, cloudinary, expressValidator;

  cloudinary = require("cloudinary");

  expressValidator = require("express-validator");

  Api = require("../api").Api;

  User = require("../models/User").User;

  module.exports = function(app) {
    app.get("/", function(req, res, next) {
      return cloudinary.api.resources(function(items) {
        var user;
        user = new User("", "", "", "");
        return res.render("index", {
          images: items.resources,
          cloudinary: cloudinary,
          user: user
        });
      });
    });
    return app.post("/", function(req, res) {
      var api, email, errors, imageID, name, password, user;
      req.assert("name", "Please enter a name").notEmpty();
      req.assert("email", "Email address too short").len(6, 64);
      req.assert("email", "Please enter a valid email").isEmail();
      req.assert("password", "Please enter a valid password").notEmpty();
      req.assert("password", "Password too short. Must be 5 characters or more.").len(5);
      errors = req.validationErrors();
      email = req.body.email;
      name = req.body.name;
      imageID = req.body.image_id;
      password = req.body.password;
      user = new User(name, email, password, imageID);
      if (errors) {
        return res.render("index", {
          cloudinary: cloudinary,
          errors: errors,
          status: "error",
          user: user
        });
      } else {
        api = new Api();
        return api.save(user, function(result) {
          return res.render("index", {
            cloudinary: cloudinary,
            status: result.status,
            user: user
          });
        });
      }
    });
  };

}).call(this);
