// Generated by CoffeeScript 1.3.3
(function() {
  var User;

  User = function(name, email, password, imageID) {
    this.name = name;
    this.email = email;
    this.password = password;
    return this.imageID = imageID;
  };

  exports.User = User;

}).call(this);
